// Code generated by baron. DO NOT EDIT.
// Rerunning baron will overwrite this file.
// Version: v0.2.2
// Version Date: 2020-10-22T14:10:11+08:00

package global

import (
	"github.com/goava/di"
)

var (
	Container *di.Container
)

func init() {
	Container, _ = di.New()
}
